# Generated by Django 4.2.6 on 2023-11-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('tx_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('block_number', models.BigIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('contract_ret', models.CharField(max_length=100)),
                ('amount', models.BigIntegerField()),
                ('owner_address', models.CharField(max_length=100)),
                ('to_address', models.CharField(max_length=100)),
            ],
        ),
    ]
